config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'
  resource :anon_share
  resources :links do
    put :set_nsfw, on: :member
    put :feature, on: :member
  	put :retry, on: :member
    get :search, on: :collection
    put :tag, on: :member
    get :desc, on: :collection
    put :hide, on: :member
    put :unhide, on: :member
    get :hidden, on: :collection
    put :untag, on: :member
    put :mark_fav, on: :member
    get :favourite, on: :collection
    put :report, on: :member
    get :statistics, on: :collection
    get :comments, on: :member
    post :create_comment, on: :member
    resources :comments, controller: 'links/comments'
  end

  get 'statistics', to: 'links#statistics'

  resources :stories

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'dashboard', to: 'home#dashboard'
  get 'accepted_responses', to: 'home#accepted_responses'
  get 'responses', to: 'home#responses'
  get 'questions', to: 'home#questions'
  get 'terms_of_use', to: 'home#terms_of_use'
  get 'privacy_policy', to: 'home#privacy_policy'
  patch 'set_gender', to: 'home#set_gender'
  get 'signin-facebook', to: 'users/omniauth_callbacks#facebook'
  get 'access_restricted', to: 'home#access_restricted'

  resources :posts, controller: 'posts' do
    put :upvote, on: :member
    put :downvote, on: :member
    resources :comments, controller: 'posts/comments' do
      put :upvote, on: :member
      put :downvote, on: :member
    end
  end
  resources :users do
    get :switch, on: :member
    get :posts, on: :member
    put :disconnect, on: :member
    get :notifications, on: :member
    get :connections, on: :collection
    resources :responses do
      put :accept, on: :member
    end
    resources :posts
  end

  resources :chats do
    put :seen, on: :member
  end

  resources :questions do
    put :reorder, on: :collection
  end

  resources :groups do
    get :dashboard, on: :member
    get :responses, on: :member
    get :search, on: :collection
    resources :responses, controller: 'groups/responses' do
      put :accept, on: :member
    end
    resources :questions, controller: 'groups/questions' do
      put :reorder, on: :collection
    end
    resources :posts, controller: 'groups/posts' do
      put :upvote, on: :member
      put :downvote, on: :member
      resources :comments, controller: 'groups/posts/comments' do
        put :upvote, on: :member
        put :downvote, on: :member
      end
    end
  end

  resources :affiliations
  get '/:permalink', to: 'home#show'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :questions
  belongs_to :user
  has_many :responses
  has_many :posts
end

app/controllers/groups/posts/comments_controller.rb
class Groups::Posts::CommentsController < ApplicationController
  before_action :check_user
  before_action :check_membership
  def new
  	@group = Group.find(params[:group_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @parent_id = params[:parent_id]
    render 'new', layout: false
  end

  def index
  	@post = Post.find(params[:post_id])
  	@comments = @post.comments.where(parent_id: params[:parent_id]).paginate(page: params[:page], per_page: 5)
  	render 'comments', layout: false
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params.merge(user_id: current_user.id))
    render 'comment', layout: false
  end

  def destroy
  	@comment = current_user.comments.find(params[:id]).destroy
  end

  def upvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: 1)
    render 'groups/posts/votes', layout: false
  end

  def downvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: -1)
    render 'groups/posts/votes', layout: false
  end

  protected

  def comments_params
  	params.require(:comment).permit(:text, :parent_id)
  end

  def check_membership
    group = Group.find params[:group_id]
    unless group.responses.where(responce_user_id: current_user.id).first || group.user_id == current_user.id
      redirect_to access_restricted_path
    end
  end
end

app/controllers/groups/posts_controller.rb
class Groups::PostsController < ApplicationController
  before_action :check_user
  before_action :check_membership
  def show
    @post = Post.find(params[:id])
  end

  def index
    @group = Group.find(params[:group_id])
    @posts = @group.posts.order('created_at DESC').paginate(per_page: 2, page: params[:page])
    render 'index', layout: false
  end

  def new
    @post = Post.new
    @group = Group.find(params[:group_id])
    render 'new', layout: false
  end

  def create
    @group = Group.find(params[:group_id])
    @post = @group.posts.create(post_params.merge(user_id: current_user.id))
    render 'post', layout: false
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  def upvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: 1)
    render 'votes', layout: false
  end

  def downvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: -1)
    render 'votes', layout: false
  end

  protected

  def check_membership
    group = Group.find params[:group_id]
    unless group.responses.where(responce_user_id: current_user.id).first || group.user_id == current_user.id
      redirect_to access_restricted_path
    end
  end  

  def post_params
    params.require(:post).permit(:text, :image, :title)
  end
end

app/controllers/groups/questions_controller.rb
class Groups::QuestionsController < ApplicationController
  before_action :check_user
  before_action :find_group
  def index
    @questions = @group.questions
  end

  def new
    @question = Question.new
    render 'new', layout: false, status: 200
  end

  def edit
    @question = @group.questions.find(params[:id])
    render 'edit', layout: false, status: 200
  end

  def create
    @question = Question.new(question_params.merge(group_id: @group.id, sequence: @group.questions.count))
    if @question.save
      render 'question', layout: false, status: 200
    else
      render 'new', layout: false, status: 422
    end
  end

  def update
    @question = @group.questions.find(params[:id])
    if @question.update(question_params)
      render 'question', layout: false, status: 200
    else
      render 'edit', layout: false, status: 422
    end
  end

  def reorder
    params[:sequence].each_with_index do |id, i|
      @group.questions.find(id).update(sequence: i)
    end
  end

  def destroy
    @question = @group.questions.find(params[:id])
    @question.destroy
  end

  protected

  def find_group
    @group = current_user.groups.find(params[:group_id])
  end

  def question_params
    params.require(:question).permit(:text)
  end
end

app/controllers/groups/responses_controller.rb
class Groups::ResponsesController < ApplicationController
  before_action :check_user, only: [:create, :accept]
  before_action :authenticate_user!, only: [:new]
  before_action :find_group
  def new
    @response = Response.new
  	@group.questions.each do |q|
      @response.answers << Answer.new(question_id: q.id)
  	end
  end

  def create
  	@response = Response.create response_params.merge(responce_user_id: current_user.id, group_id: @group.id)
    flash[:notice] = "Requested to join #{@response.group.name}'s questions"
    if @response.responce_user_id == @response.group.user_id
      @response.delete
    else
      ResponseMailer.with(response_user: @response.responce_user, group: @response.group).new_response_to_group.deliver_later
    end
    redirect_to root_path
  end

  def accept
    unless @group.user == current_user
      redirect_to access_restricted_path
    end
    @response = @group.responses.find(params[:id])
    @response.update(accepted: true)
    render 'accept', layout: false
    ResponseMailer.with(group: @group, response_user: @response.responce_user).response_to_group_accepted.deliver_later
  end

  protected

  def find_group
    @group = Group.find(params[:group_id])
  end

  def response_params
    params.permit(:response).permit(:user_id, :answers_attributes => [:question_id, :text])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_user
  before_action :find_group, only: [:dashboard, :responses]
  def index
    @groups = current_user.groups
    @other_groups = Group.find_by_sql(
      current_user.posted_responses.where(accepted: true).joins(:group).select('groups.*').to_sql
    )
  end

  def search
    @groups = Group.where("name ~* '#{params[:query]}' or description ~* '#{params[:query]}'").paginate(page: params[:page], per_page: 5)
    render 'groups', layout: false
  end

  def show
    @group = Group.find(params[:id])
    unless @group.user == current_user || current_user.posted_responses.where(group_id: @group.id).first.present?
      redirect_to new_group_response_path(@group)
    end
    @posts = @group.posts.order('created_at DESC').paginate(page: params[:page], per_page: 2)
  end

  def dashboard
    @group = current_user.groups.find(params[:id])
    @questions = @group.questions
    @responses = get_responses.paginate(page: 1, per_page: 2)
  end

  def responses
    @responses = get_responses.paginate(page: params[:page], per_page: 2)
    render 'responses', layout: false
  end

  def new
    @group = Group.new
    render 'new', layout: false, status: 200
  end

  def edit
    @group = current_user.groups.find(params[:id])
    render 'edit', layout: false, status: 200
  end

  def create
    @group = Group.new(group_params.merge(user_id: current_user.id))
    if @group.save
      render 'group', layout: false, status: 200
    else
      render 'new', layout: false, status: 422
    end
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      render 'group', layout: false, status: 200
    else
      render 'edit', layout: false, status: 422
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    render json: {message: 'group deleted'}
  end

  layout 'network'

  protected

  def find_group
    @group = current_user.groups.find(params[:id])
  end

  def get_responses
    responses = @group.responses.order('id DESC')
    if params[:state] == 'accepted'
      responses.where(accepted: true)
    else
      responses.where(accepted: false)
    end
  end

  def group_params
    params.require(:group).permit(:description, :name)
  end
end

app/views/groups/_form.html.haml
= simple_form_for @group, remote: true do |f|
  = f.input :name
  = f.input :description
  .clearfix
  = f.submit 'Submit', class: 'btn-primary'
  .clearfix
  = link_to 'cancel', '#', class: 'cancel-form', remote: true

app/views/groups/_group.html.haml
.question
  %h3
    = link_to group.name, group_path(group)
  %p
    = group.description
  - if actions
    .question-actions
      .pull-left
        = link_to 'Edit', edit_group_path(group), remote: true, class: 'edit-question'
      .pull-left
        = link_to 'delete', group_path(group), method: 'delete', remote: true, class: 'delete-question'
      .pull-left
        = link_to 'dashboard', dashboard_group_path(group)
      .clearfix
  .question-edit-form-container

app/views/groups/_groups.html.haml
- groups.each do |g|
  = render partial: 'groups/group', locals: {group: g, actions: false}
.more-responses
  - if groups.next_page
    = link_to 'View more', search_groups_path(query: params[:query], page: (params[:page].present? ? params[:page].to_i + 1 : 2)), remote: true, class: 'view-more'

app/views/groups/_responses.html.haml
- @responses.each do |r|
  .question
    = render partial: 'users/user_details', locals: {user: r.responce_user}
    .clearfix
    .answers
      - r.answers.joins(:question).each do |a|
        .answer  
          .question-text.pull-left.col-lg-5.col-sm-5.col-xs-12
            = a.question.text
          .answer-text.pull-right.col-lg-5.col-sm-5.col-xs-12
            = a.text
          .clearfix
    .answer-action
      - if r.accepted
        = render partial: 'groups/responses/accept', locals: {user: r.responce_user}
      - else
        = link_to 'Accept', accept_group_response_path(@group, r), remote: true, class: 'accept-response', method: 'put'
- if @responses.next_page
  .more-responses
    = link_to 'View more', responses_group_path(@group, state: state, page: params[:page].present? ? params[:page].to_i + 1 : 2), remote: true, class: 'view-more'

app/views/groups/dashboard.html.haml
.my-space.my-responses.col-lg-8.col-sm-6.col-xs-12.pull-left
  %h3
    Responses
  .response-filters
    = link_to 'new responses', responses_group_path(state: 'new'), class: 'filter-response-link', remote: true
    = link_to 'accepted responses', responses_group_path(state: 'accepted'), class: 'filter-response-link', remote: true
  .responses-container
    = render partial: 'responses', locals: {state: 'new'}

.my-space.col-lg-4.col-sm-6.col-xs-12.pull-left
  %h3
    Entrance Questions
  - if @questions.count == 0
    .question.help-text
      %p
        You haven't created any questions. Ask something that seeks the viewpoint of the person you want to add to this group.
  .questions-container.reorderable
    - @questions.each do |question|
      = render partial: 'groups/questions/question', locals: {question: question}
  .new-question
  .questions-actions
    = link_to 'Add question', new_group_question_path(@group), class: 'add-question', remote: true
    = link_to 'Preview', new_group_response_path(@group)

app/views/groups/edit.html.haml
= render partial: 'form'

app/views/groups/group.html.haml
= render partial: 'group', locals: {group: @group, actions: true}

app/views/groups/groups.html.haml
= render partial: 'groups/groups', locals: {groups: @groups}

app/views/groups/index.html.haml
.my-space.col-lg-4.col-sm-6.col-12.pull-left
  .responses-container
    %h3 My Groups
    - @groups.each do |group|
      = render partial: 'group', locals: {group: group, actions: true}
    - @other_groups.each do |group|
      = render partial: 'group', locals: {group: group, actions: false}
  .new-question
  .questions-actions
    = link_to 'New Group', new_group_path, class: 'add-question', remote: true
  .questions-container
.my-space.col-lg-8.col-sm-6.col-12.pull-left
  %h3
    Find Groups
  .search
    Search
    = text_field_tag 'search',nil, data: {url: search_groups_path(page: 1)}
  .clearfix
  .questions
    = render partial: 'groups/groups', locals: {groups: Group.order('created_at DESC').paginate(page: 1, per_page: 5)}

app/views/groups/new.html.haml
= render partial: 'form'

app/views/groups/responses.html.haml
= render partial: 'responses', locals: {state: params[:state] || 'new'}

app/views/groups/show.html.haml
.my-space
  %h3
    = @group.name
  .questions-container
    .group-action
      = link_to 'New post', new_group_post_path(@group), remote: true, class: 'new-group-post'
    .new-post
    .posts
      = render partial: 'groups/posts/posts', locals: {posts: @posts}