config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'
  resource :anon_share
  resources :links do
    put :set_nsfw, on: :member
    put :feature, on: :member
  	put :retry, on: :member
    get :search, on: :collection
    put :tag, on: :member
    get :desc, on: :collection
    put :hide, on: :member
    put :unhide, on: :member
    get :hidden, on: :collection
    put :untag, on: :member
    put :mark_fav, on: :member
    get :favourite, on: :collection
    put :report, on: :member
    get :statistics, on: :collection
    get :comments, on: :member
    post :create_comment, on: :member
    resources :comments, controller: 'links/comments'
  end

  get 'statistics', to: 'links#statistics'

  resources :stories

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'dashboard', to: 'home#dashboard'
  get 'accepted_responses', to: 'home#accepted_responses'
  get 'responses', to: 'home#responses'
  get 'questions', to: 'home#questions'
  get 'terms_of_use', to: 'home#terms_of_use'
  get 'privacy_policy', to: 'home#privacy_policy'
  patch 'set_gender', to: 'home#set_gender'
  get 'signin-facebook', to: 'users/omniauth_callbacks#facebook'
  get 'access_restricted', to: 'home#access_restricted'

  resources :posts, controller: 'posts' do
    put :upvote, on: :member
    put :downvote, on: :member
    resources :comments, controller: 'posts/comments' do
      put :upvote, on: :member
      put :downvote, on: :member
    end
  end
  resources :users do
    get :switch, on: :member
    get :posts, on: :member
    put :disconnect, on: :member
    get :notifications, on: :member
    get :connections, on: :collection
    resources :responses do
      put :accept, on: :member
    end
    resources :posts
  end

  resources :chats do
    put :seen, on: :member
  end

  resources :questions do
    put :reorder, on: :collection
  end

  resources :groups do
    get :dashboard, on: :member
    get :responses, on: :member
    get :search, on: :collection
    resources :responses, controller: 'groups/responses' do
      put :accept, on: :member
    end
    resources :questions, controller: 'groups/questions' do
      put :reorder, on: :collection
    end
    resources :posts, controller: 'groups/posts' do
      put :upvote, on: :member
      put :downvote, on: :member
      resources :comments, controller: 'groups/posts/comments' do
        put :upvote, on: :member
        put :downvote, on: :member
      end
    end
  end

  resources :affiliations
  get '/:permalink', to: 'home#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_user, only: [:dashboard, :responses, :accepted_responses]
  def show
  	@questions = get_questions.paginate(page: 1, per_page: 8)
    if current_user
      @connections = [current_user] + connections_for(current_user)
    else
      @connections = []
    end
  end

  def questions
    @questions = get_questions.paginate(page: params[:page], per_page: 8)
    render 'questions', layout: false
  end

  def dashboard
    @questions = current_user.questions.order('sequence ASC')
    @responses = get_responses.paginate(page: 1, per_page: 2)
 	  @accepted_responses = get_accepted_responses.paginate(page: 1, per_page: 5)
  end

  def responses
    @responses = get_responses.paginate(page: params[:page], per_page: 2)
    render 'responses', layout: false
  end

  def accepted_responses
  	@accepted_responses = get_accepted_responses.paginate(page: params[:page], per_page: 5)
  	render 'accepted_responses', layout: false
  end

  def terms_of_use

  end

  def privacy_policy

  end

  def set_gender
    current_user.update_attributes(gender_params)
  end

  def access_restricted
  end

  layout 'network'

  protected

  def gender_params
    params.require(:user).permit(:gender)
  end

  def get_accepted_responses
  	current_user.posted_responses.where(accepted: true).order('updated_at DESC')
  end

  def get_responses
    responses = current_user.responses.order('id DESC')
    if params[:state] == 'accepted'
      responses.where(accepted: true)
    else
      responses.where(accepted: false)
    end
  end

  def get_questions
    questions = Question.joins(:user).order('id DESC')
    if params[:query]
      questions = questions.joins(:user).where("questions.text ~* '#{params[:query]}' or users.name ~* '#{params[:query]}'")
      "LOWER(questions.text) like LOWER('%#{params[:query]}%') or LOWER(users.name) like LOWER('%#{params[:query]}%')"
    end
    questions
  end
end

app/views/home/_accepted_responses.html.haml
- @accepted_responses.each do |r|
  .question
    .pull-left.user-details
      = image_tag r.responce_user.image.url(:thumb)
      = "#{r.responce_user.name} accepted your response."
      = link_to 'leave a chat', connections_users_path(user_id: r.responce_user_id), class: 'leave-chat pull-right'
    .clearfix
- if @accepted_responses.next_page
  .more-responses
    = link_to 'View more', accepted_responses_path(page: params[:page].present? ? params[:page].to_i + 1 : 2), remote: true, class: 'view-more'

app/views/home/_gender_form.html.haml
= simple_form_for current_user, url: set_gender_path, html: {class: 'white gender_form'} do |f|
  = f.label 'set your gender'
  = f.collection_radio_buttons :gender, ['male', 'female', 'others'], :to_s, :to_s

app/views/home/_questions.html.haml
- @questions.each do |q|
  .question-small
    .user-details.float-left
      .avathar= image_tag q.user.image.url(:thumb)
    .question-small-body
      %h3= link_to(q.user.name, user_posts_path(q.user))
      %p= auto_link q.text, html: {target: '_blank'}
      = link_to new_user_response_path(q.user), class: 'connect-icon' do
        = image_tag('https://miro.medium.com/max/1200/1*2hod4Lwb9wDrzSTLFVcpOg@2x.png', class: 'float-right connect-icon-img')
    .clearfix

.clearfix
- if @questions.next_page
  .more-responses.more-questions.question-wraper.view-more-questions-container
    = link_to 'View more', questions_path(query: params[:query], page: params[:page].present? ? params[:page].to_i + 1 : 2), remote: true, class: 'view-more view-more-questions'

- if @questions.length == 0 && params[:query].present?
  No results

app/views/home/_responses.html.haml
- @responses.each do |r|
  .question
    = render partial: 'users/user_details', locals: {user: r.responce_user}
    .clearfix
    .answers
      - r.answers.joins(:question).each do |a|
        .answer  
          .question-text.pull-left.col-lg-5.col-sm-5.col-xs-12
            = a.question.text
          .answer-text.pull-right.col-lg-5.col-sm-5.col-xs-12
            = a.text
          .clearfix
    .answer-action
      - if r.accepted
        = render partial: 'responses/accept', locals: {user: r.responce_user}
      - else
        = link_to 'Accept', accept_user_response_path(r.user, r), remote: true, class: 'accept-response', method: 'put'
- if @responses.next_page
  .more-responses
    = link_to 'View more', responses_path(state: state, page: params[:page].present? ? params[:page].to_i + 1 : 2), remote: true, class: 'view-more'

app/views/home/accepted_responses.html.haml
= render partial: 'accepted_responses'

app/views/home/access_restricted.html.haml
.new-response
  %h3
    You dont have access to this resource
  .actions
    = link_to 'sign in', new_user_session_path
    %br
    = link_to 'sign up', new_user_registration_path

app/views/home/dashboard.html.haml
.my-space.my-responses.col-lg-8.col-sm-6.col-xs-12.pull-left
  %h3
    Responses
  .response-filters
    = link_to 'new responses', responses_path(state: 'new'), class: 'filter-response-link', remote: true
    = link_to 'accepted responses', responses_path(state: 'accepted'), class: 'filter-response-link', remote: true
  .responses-container
    = render partial: 'responses', locals: {state: 'new'}

.my-space.col-lg-4.col-sm-6.col-xs-12.pull-left
  .accepted-responses
    = render partial: 'accepted_responses'

  %h3
    My Questions
  - if @questions.count == 0
    .question.help-text
      %p
        You haven't created any questions. Ask something that seeks the viewpoint of the person you want to connect.
  .questions-container.reorderable
    - @questions.each do |question|
      = render partial: 'questions/question', locals: {question: question}
  .new-question
  .questions-actions
    = link_to 'Add question', new_question_path, class: 'add-question', remote: true
    = link_to 'Preview', new_user_response_path(current_user)

app/views/home/questions.html.haml
= render partial: 'questions'

app/views/home/responses.html.haml
= render partial: 'responses', locals: {state: params[:state] || 'new'}

app/views/home/show.html.haml
- content_for :head do
  %title
    Date with Like-minded people
%h1.name.description.black
  Serious dating site for finding like-minded partners!!

.search.pull-right
  Search
  = text_field_tag 'search', nil, data: {url: questions_path(page: 1)}
.clearfix

.questions
  = render partial: 'questions'
- if false
  = render template: 'home/neibhourhood/neibhourhood'  