config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'
  resource :anon_share
  resources :links do
    put :set_nsfw, on: :member
    put :feature, on: :member
  	put :retry, on: :member
    get :search, on: :collection
    put :tag, on: :member
    get :desc, on: :collection
    put :hide, on: :member
    put :unhide, on: :member
    get :hidden, on: :collection
    put :untag, on: :member
    put :mark_fav, on: :member
    get :favourite, on: :collection
    put :report, on: :member
    get :statistics, on: :collection
    get :comments, on: :member
    post :create_comment, on: :member
    resources :comments, controller: 'links/comments'
  end

  get 'statistics', to: 'links#statistics'

  resources :stories

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'dashboard', to: 'home#dashboard'
  get 'accepted_responses', to: 'home#accepted_responses'
  get 'responses', to: 'home#responses'
  get 'questions', to: 'home#questions'
  get 'terms_of_use', to: 'home#terms_of_use'
  get 'privacy_policy', to: 'home#privacy_policy'
  patch 'set_gender', to: 'home#set_gender'
  get 'signin-facebook', to: 'users/omniauth_callbacks#facebook'
  get 'access_restricted', to: 'home#access_restricted'

  resources :posts, controller: 'posts' do
    put :upvote, on: :member
    put :downvote, on: :member
    resources :comments, controller: 'posts/comments' do
      put :upvote, on: :member
      put :downvote, on: :member
    end
  end
  resources :users do
    get :switch, on: :member
    get :posts, on: :member
    put :disconnect, on: :member
    get :notifications, on: :member
    get :connections, on: :collection
    resources :responses do
      put :accept, on: :member
    end
    resources :posts
  end

  resources :chats do
    put :seen, on: :member
  end

  resources :questions do
    put :reorder, on: :collection
  end

  resources :groups do
    get :dashboard, on: :member
    get :responses, on: :member
    get :search, on: :collection
    resources :responses, controller: 'groups/responses' do
      put :accept, on: :member
    end
    resources :questions, controller: 'groups/questions' do
      put :reorder, on: :collection
    end
    resources :posts, controller: 'groups/posts' do
      put :upvote, on: :member
      put :downvote, on: :member
      resources :comments, controller: 'groups/posts/comments' do
        put :upvote, on: :member
        put :downvote, on: :member
      end
    end
  end

  resources :affiliations
  get '/:permalink', to: 'home#show'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :post_user, class_name: 'User', optional: true
  belongs_to :user
  belongs_to :group, optional: true
  has_many :votes
  has_many :comments
  before_destroy :cancel_notifications

  def under
    self
  end

  after_create :notify_connections

  default_scope -> {order('created_at DESC')}

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  validates :title, presence: true

  def cancel_notifications
    Notification.where(target_id: id, target_type: 'Post').delete_all
  end

  def upvote_count
    votes.where(weight: 1).count
  end

  def downvote_count
    votes.where(weight: -1).count
  end

  def self.search(q, user)
    condition = match_stmt(q)
    FilterPost.filter(Post.where(condition), [:text, :title], user)
  end

  def self.match_stmt(q)
    keys = q.to_s.split(/[ .\n=;,&%]/)
    keys.map{|key| "posts.title ~* '#{key}' or posts.text ~* '#{key}'"}.join(' and ')
  end

  def self.get_all(user)
    FilterPost.filter(Post.all, [:text, :title], user)
  end

  def self.latest_for(user)
    FilterPost.filter(Feed.new(user).get, [:text, :title], user)
  end

  def notify_connections
    Connection.where(to_user_id: user_id).map(&:user).each do |user|
      Notifier.perform_now_or_later user, 'create', self
    end
  end
end

app/controllers/groups/posts/comments_controller.rb
class Groups::Posts::CommentsController < ApplicationController
  before_action :check_user
  before_action :check_membership
  def new
  	@group = Group.find(params[:group_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @parent_id = params[:parent_id]
    render 'new', layout: false
  end

  def index
  	@post = Post.find(params[:post_id])
  	@comments = @post.comments.where(parent_id: params[:parent_id]).paginate(page: params[:page], per_page: 5)
  	render 'comments', layout: false
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params.merge(user_id: current_user.id))
    render 'comment', layout: false
  end

  def destroy
  	@comment = current_user.comments.find(params[:id]).destroy
  end

  def upvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: 1)
    render 'groups/posts/votes', layout: false
  end

  def downvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: -1)
    render 'groups/posts/votes', layout: false
  end

  protected

  def comments_params
  	params.require(:comment).permit(:text, :parent_id)
  end

  def check_membership
    group = Group.find params[:group_id]
    unless group.responses.where(responce_user_id: current_user.id).first || group.user_id == current_user.id
      redirect_to access_restricted_path
    end
  end
end

app/controllers/groups/posts_controller.rb
class Groups::PostsController < ApplicationController
  before_action :check_user
  before_action :check_membership
  def show
    @post = Post.find(params[:id])
  end

  def index
    @group = Group.find(params[:group_id])
    @posts = @group.posts.order('created_at DESC').paginate(per_page: 2, page: params[:page])
    render 'index', layout: false
  end

  def new
    @post = Post.new
    @group = Group.find(params[:group_id])
    render 'new', layout: false
  end

  def create
    @group = Group.find(params[:group_id])
    @post = @group.posts.create(post_params.merge(user_id: current_user.id))
    render 'post', layout: false
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  def upvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: 1)
    render 'votes', layout: false
  end

  def downvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: -1)
    render 'votes', layout: false
  end

  protected

  def check_membership
    group = Group.find params[:group_id]
    unless group.responses.where(responce_user_id: current_user.id).first || group.user_id == current_user.id
      redirect_to access_restricted_path
    end
  end  

  def post_params
    params.require(:post).permit(:text, :image, :title)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.for_post.where(parent_id: params[:parent_id]).paginate(page: params[:page], per_page: 5)
    @comments = FilterPost.filter(@comments,[:text], current_user.try(:badwords))
    render 'comments', layout: false
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.for_post.create(comments_params.merge(user_id: current_user.id))
    render 'posts/comments/comment', layout: false
  end

  def destroy
    @comment = current_user.comments.find(params[:id]).destroy
  end

  def upvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: 1) if @comment.user != current_user
    render 'posts/comment_actions', layout: false
  end

  def downvote
    @post = @comment = Comment.find(params[:id])
    current_vote = @comment.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, comment_id: params[:id], weight: -1) if @comment.user != current_user
    render 'posts/comment_actions', layout: false
  end

  protected

  def comments_params
    params.require(:comment).permit(:text, :parent_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, only: [:downvote, :upvote, :destroy, :create]
  def show
    @post = Post.find(params[:id])
  end

  def index
    if params[:query].present?
      @posts = Post.search(params[:query], current_user)
      @posts = @posts.paginate(per_page: 12, page: params[:page])
      mark_seen(@posts)
    else
      @posts = Post.latest_for(current_user)
      @posts = @posts.paginate(per_page: 12, page: params[:page])
      mark_seen(@posts)
    end

    @next_path = posts_path(page: (params[:page].present? ? params[:page].to_i + 1 : 2))

    if request.format.html?
      render 'index'
    else
      render 'posts', layout: false
    end
  end

  def new
    @post = Post.new
    if current_user
      render 'new', layout: false
    else
      render 'devise/sessions/new', layout: false
    end
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if(@post.save)
      render 'post', layout: false
    else 
      render 'new', layout: false, status: 422
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  def upvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete      
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: 1) if @post.user != current_user
    render 'comment_actions', layout: false
  end

  def downvote
    @post = Post.find(params[:id])
    current_vote = @post.votes.where(user_id: current_user.id).first
    if current_vote
      current_vote.delete
    end
    Vote.create(user_id: current_user.id, post_id: params[:id], weight: -1) if @post.user != current_user
    render 'comment_actions', layout: false
  end

  layout 'network'

  protected

  def mark_seen(posts)
    return unless current_user.present?
    posts.group_by(&:user_id).each do |user_id, ps|
      Connection.where(user_id: current_user.id, to_user_id: user_id).first.try(:update, last_seen_post_id: ps.max_by(&:id).id)
    end
  end

  def post_params
    params.require(:post).permit(:text, :image, :title)
  end
end

app/views/posts/_comment_actions.html.haml
.comment-actions
  - if post.is_a? Post
    - upvote_link = upvote_post_path(post || @link)
    - downvote_link = downvote_post_path(post || @link)
  - else
    - upvote_link = upvote_post_comment_path(post.under, post)
    - downvote_link = downvote_post_comment_path(post.under, post)

  = link_to "#{post.upvote_count} upvotes", upvote_link, remote: true, method: :put, class: 'cast-vote'
  = link_to (post.is_a?(Comment) ? 'Reply' : 'new comment'), new_post_comment_path(post.is_a?(Post) ? post : post.under, parent_id: (post.is_a?(Post) ? nil : post.id), class_name: (post.under.is_a?(Link) ? 'link' : 'post')), remote: true, class: 'new-comment-link comment-action pull-left'
  - if post.is_a?(Post) && post.comments.count > 0
    = link_to "show #{post.comments.count} comment#{post.comments.count > 1 ? 's' : ''}", post_comments_path(post), remote: true, class: 'expand-comment comment-action pull-left'
  - if post.is_a?(Post)
    = link_to 'share', "https://www.facebook.com/sharer/sharer.php?u=#{URI.encode post_url(post)}", class: 'share'
    

app/views/posts/_post.html.haml
.group-post.post
  .post-actions.pull-right
    - if post.user == current_user
      = link_to 'delete', post_path(post), remote: true, method: :delete, class: 'delete-post'
  .clearfix
  .post-title
    %h2= link_to post.title, post_path(post)
  .post-body
    = auto_link post.text, html: {target: '_blank'}
    - if post.image.present?
      = image_tag post.image.url(:original), class: 'post-image'
  .clearfix
  .pull-right.user-avathar= render partial: 'users/user_details', locals: {user: post.user}
  .clearfix
  = render partial: 'posts/comment_actions', locals: {post: post}
  .clearfix
  .new-comment
  .comments-container{class: params[:comment_id].present? ? '' : 'd-none'}
    .comments
      - if params[:comment_id]
        - comment = post.comments.find(params[:comment_id])
      - if comment
        = render partial: 'posts/comments/comment', locals: {expand: true, new: false, comment: comment.parent || comment}
  

app/views/posts/_posts.html.haml
.posts
  - posts.each do |p|
    = render partial: 'posts/post', locals: {post: p}
.more-responses
- if @posts.next_page
  = link_to 'View more', @next_path, remote: true, class: 'view-more'

app/views/posts/comment_actions.html.haml
= render partial: 'posts/comment_actions', locals: {post: @post}

app/views/posts/index.html.haml
.questions-container
  .search.pull-right
    Search
    = text_field_tag 'search',nil, data: {url: posts_path(page: 1)}
  .clearfix
  .group-action
    = link_to 'New post', new_post_path, remote: true, class: 'new-group-post'
  .new-post
  = render partial: 'posts', locals: {posts: @posts}

app/views/posts/new.html.haml
= simple_form_for([@group, @post], remote: true, html: { class: 'post-form' }) do |f|
  = f.input :title
  = f.input :text
  = link_to 'Add image', '#', remote: true, class: 'open-image-upload'
  .image-upload
    = f.input :image, label: 'Upload image'
  .clearfix
  = f.submit :post, class: 'btn-primary'
  = link_to 'cancel', '#', class: 'cancel-form', remote: true

app/views/posts/post.html.haml
= render partial: 'post', locals: {post: @post}

app/views/posts/posts.html.haml
= render partial: 'posts', locals: {posts: @posts}

app/views/posts/show.html.haml
.questions-container
  .posts
    = render partial: 'posts/post', locals: {post: @post}