config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'
  resource :anon_share
  resources :links do
    put :set_nsfw, on: :member
    put :feature, on: :member
  	put :retry, on: :member
    get :search, on: :collection
    put :tag, on: :member
    get :desc, on: :collection
    put :hide, on: :member
    put :unhide, on: :member
    get :hidden, on: :collection
    put :untag, on: :member
    put :mark_fav, on: :member
    get :favourite, on: :collection
    put :report, on: :member
    get :statistics, on: :collection
    get :comments, on: :member
    post :create_comment, on: :member
    resources :comments, controller: 'links/comments'
  end

  get 'statistics', to: 'links#statistics'

  resources :stories

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'dashboard', to: 'home#dashboard'
  get 'accepted_responses', to: 'home#accepted_responses'
  get 'responses', to: 'home#responses'
  get 'questions', to: 'home#questions'
  get 'terms_of_use', to: 'home#terms_of_use'
  get 'privacy_policy', to: 'home#privacy_policy'
  patch 'set_gender', to: 'home#set_gender'
  get 'signin-facebook', to: 'users/omniauth_callbacks#facebook'
  get 'access_restricted', to: 'home#access_restricted'

  resources :posts, controller: 'posts' do
    put :upvote, on: :member
    put :downvote, on: :member
    resources :comments, controller: 'posts/comments' do
      put :upvote, on: :member
      put :downvote, on: :member
    end
  end
  resources :users do
    get :switch, on: :member
    get :posts, on: :member
    put :disconnect, on: :member
    get :notifications, on: :member
    get :connections, on: :collection
    resources :responses do
      put :accept, on: :member
    end
    resources :posts
  end

  resources :chats do
    put :seen, on: :member
  end

  resources :questions do
    put :reorder, on: :collection
  end

  resources :groups do
    get :dashboard, on: :member
    get :responses, on: :member
    get :search, on: :collection
    resources :responses, controller: 'groups/responses' do
      put :accept, on: :member
    end
    resources :questions, controller: 'groups/questions' do
      put :reorder, on: :collection
    end
    resources :posts, controller: 'groups/posts' do
      put :upvote, on: :member
      put :downvote, on: :member
      resources :comments, controller: 'groups/posts/comments' do
        put :upvote, on: :member
        put :downvote, on: :member
      end
    end
  end

  resources :affiliations
  get '/:permalink', to: 'home#show'
end

app/models/anon_share.rb
require 'openssl'
class AnonShare < ActiveRecord::Base
  self.table_name = 'posts'
  attr_accessor :user_name

  def encrypt
    content = {
      text: text,
      title: title,
      user_name: user_name
    }.to_json

    cipher = OpenSSL::Cipher.new('DES-EDE3-CBC').encrypt
    cipher.key = Digest::SHA1.hexdigest KEY
    s = cipher.update(content) + cipher.final

    s.unpack('H*')[0].upcase
  end

  def self.decrypt(encrypted_content)
    cipher = OpenSSL::Cipher.new('DES-EDE3-CBC').decrypt
    cipher.key = Digest::SHA1.hexdigest KEY
    s = [encrypted_content].pack("H*").unpack("C*").pack("c*")

    decrypted = cipher.update(s) + cipher.final
    self.new(JSON.parse(decrypted))
  end

  KEY = '1AFCDE3EAA'
end

app/controllers/anon_shares_controller.rb
class AnonSharesController < ApplicationController
  def show
    @anon_share = AnonShare.decrypt(params[:says])
  end

  def create
    redirect_to anon_share_path(says: AnonShare.new(params.require(:anon_share).permit(:title, :user_name, :text)).encrypt)
  end

  def edit
    if params[:says].present?
      @anon_share = AnonShare.decrypt(params[:says])
    else
      @anon_share = AnonShare.new
    end
  end

  layout 'network'
end

app/views/anon_shares/_anon_share.haml
.anon-share
  %h1= @anon_share.title
  = image_tag('https://image.flaticon.com/icons/svg/1380/1380338.svg')
  %p= raw @anon_share.text
  .float-left
    = link_to 'share', "https://www.facebook.com/sharer/sharer.php?u=#{URI.encode(anon_share_url(says: params[:says]))}", class: 'anon-share-share-btn'
  .float-right= @anon_share.user_name

app/views/anon_shares/create.haml
= render partial: 'anon_share'

app/views/anon_shares/edit.haml
.ads
  .ad
    Use This Funtionality when not logged to avoid Online Footprints
%h1
  Prepare your post
.question.response-form
  = form_for @anon_share, url: anon_share_path do |f|
    .form-group
      Title
      = f.text_field :title, class: 'form-control'
    .form-group
      Body
      = f.text_area :text, class: 'form-control'
    .form-group
      Your name(if you want to share)
      = f.text_field :user_name, class: 'form-control'
    = f.submit

app/views/anon_shares/show.haml
= render partial: 'anon_share'
= link_to 'speak something without beeing caught', edit_anon_share_path, class: 'anon-share-share-btn'
.blank
.ads
  .ad
    %h2
      How It Works
    %p
      Content posted are never stored in our servers in ANY FORM, but it is encrypted and stored in the shared url itself. If this functionality is unavailable, tou can try decrypting the content using ssl public key "1AFCDE3EAA" without quotes. post content is under parameter named "says" in url.